# Generated by Django 4.2.18 on 2025-04-03 22:25

from django.db import migrations, models
import django.db.models.deletion
import properties.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('whatsapp_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('current_state', models.CharField(default='initial', max_length=100)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('context_data', models.JSONField(blank=True, default=dict)),
            ],
            bases=(models.Model, properties.models.BaseSessionMixin),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='properties.landlord')),
            ],
        ),
        migrations.CreateModel(
            name='RentEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_entities', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='UnidentifiedUser',
            fields=[
                ('whatsapp_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('current_state', models.CharField(default='initial', max_length=100)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('context_data', models.JSONField(blank=True, default=dict)),
            ],
            bases=(models.Model, properties.models.BaseSessionMixin),
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100, unique=True)),
                ('sender_id', models.CharField(max_length=20)),
                ('message_type', models.CharField(max_length=20)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('timestamp', models.CharField(max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('whatsapp_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('start_of_payment_cycle', models.DateField()),
                ('bills_due_date', models.DateField()),
                ('last_rent_paid', models.DateField(blank=True, null=True)),
                ('last_bill_paid', models.DateField(blank=True, null=True)),
                ('payment_cycle_months', models.PositiveIntegerField(default=1)),
                ('current_state', models.CharField(default='initial', max_length=100)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('rent_entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='properties.rententity')),
            ],
            bases=(models.Model, properties.models.BaseSessionMixin),
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('months_paid', models.PositiveIntegerField(default=1)),
                ('receipt_number', models.CharField(max_length=20, unique=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='properties.tenant')),
            ],
        ),
    ]
