# Generated by Django 4.2.20 on 2025-03-19 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(max_length=20, unique=True)),
                ('is_landlord', models.BooleanField(blank=True, null=True)),
                ('current_state', models.CharField(max_length=100)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('context_data', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='property',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='rent_amount',
        ),
        migrations.AddField(
            model_name='landlord',
            name='whatsapp_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='whatsapp_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='RentEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_entities', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('months_paid', models.PositiveIntegerField(default=1)),
                ('receipt_number', models.CharField(max_length=20, unique=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='properties.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='tenant',
            name='rent_entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='properties.rententity'),
        ),
    ]
